@startuml
'https://plantuml.com/class-diagram

package "entite"
{
/'Définitions des classes'/
abstract Entite<<abstract>>
{
#m_nom : String
#m_pv : Integer
#m_force : Integer
#m_dexterite : Integer
#m_vitesse : Integer
#m_initiative : Integer

+getNom():String
+getPv():Integer
+getForce():Integer
+getDexterite():Integer
+getVitesse():Integer
+getInitiative():Integer
+setPv(pv:Integer)
+attaquer()
+seDeplacer()
+toString():String

}
class Personnage
class Monstre
package "classe"
{
abstract Classe<<abstract>>
class Clerc
class Guerrier
class Magicien
class Roublard
}

package "race"
{
/'Définitions des classes'/
abstract Race<<abstract>>
{
#m_pv : Integer
#m_force : Integer
#m_dexterite : Integer
#m_vitesse : Integer
#m_initiative : Integer
+getPv():Integer
+getForce():Integer
+getDexterite():Integer
+getVitesse():Integer
+getInitiative():Integer
+toString():String
}
class Elfe
class Humain
class Halfelin
class Nain
}

/'Définitions des relations'/
Personnage -up-|> Entite
Monstre -up-|> Entite

Clerc -up-|> Classe
Guerrier -up-|> Classe
Magicien -up-|> Classe
Roublard -up-|> Classe

Elfe -up-|> Race
Humain -up-|> Race
Halfelin -up-|> Race
Nain -up-|> Race

}
package "equipement"
{
/'Définitions des classes'/
abstract equipement<<abstract>>
{

}
/'Définitions des relations'/

}
package "plateau"
{
/'Définitions des classes'/

/'Définitions des relations'/
}

@enduml